apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml --out k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: nextjs
  name: nextjs
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: nextjs
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml --out k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: nextjs
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
          image: elyxium/frontend-parcelas:latest
          name: nextjs
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:fURIYYERdyxYQPtKqKvFqunPcSBVXixg@tramway.proxy.rlwy.net:23083/railway"
            - name: NEXTAUTH_URL
              value: "http://localhost:3000"
            - name: NEXTAUTH_SECRET
              value: "secreto12"
            - name: AUTH_SECRET
              value: "tyiMXD2xSJ1vm+4sEt3BiA81DTUMj8UYmrrLnrf48jQ="
      restartPolicy: Always
